/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Starter API
 * Backend API for the starter template
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customClient } from './api-client';
export interface HealthDto {
  ok: boolean;
}

export interface AuthLoginBodyDto {
  email: string;
  password: string;
  rememberMe?: boolean;
}

export interface AuthLoginResponseDto {
  accessToken: string;
  tokenType: string;
}

export interface AuthSignupBodyDto {
  organizationName: string;
  name: string;
  email: string;
  /** @minLength 8 */
  password: string;
  acceptTerms: boolean;
  planCode?: string;
}

export interface ForgotPasswordBodyDto {
  email: string;
}

export interface AuthMessageResponseDto {
  message: string;
}

export interface ResetPasswordBodyDto {
  token: string;
  /** @minLength 8 */
  password: string;
}

export interface MeUserDto {
  id: string;
  email: string;
  /** @nullable */
  name: string | null;
  isPlatformOwner: boolean;
}

export type MeOrganizationDtoType = typeof MeOrganizationDtoType[keyof typeof MeOrganizationDtoType];


export const MeOrganizationDtoType = {
  workspace: 'workspace',
} as const;

export type MeOrganizationDtoMembershipStatus = typeof MeOrganizationDtoMembershipStatus[keyof typeof MeOrganizationDtoMembershipStatus];


export const MeOrganizationDtoMembershipStatus = {
  invited: 'invited',
  active: 'active',
  suspended: 'suspended',
} as const;

export interface MeOrganizationDto {
  id: string;
  name: string;
  type: MeOrganizationDtoType;
  isActive: boolean;
  membershipStatus: MeOrganizationDtoMembershipStatus;
  isOwner: boolean;
}

export type MeRoleDtoContextType = typeof MeRoleDtoContextType[keyof typeof MeRoleDtoContextType];


export const MeRoleDtoContextType = {
  platform: 'platform',
  organization: 'organization',
} as const;

export interface MeRoleDto {
  id: string;
  name: string;
  contextType: MeRoleDtoContextType;
  /** @nullable */
  organizationId: string | null;
  isSystem: boolean;
}

export type MePermissionDtoContextType = typeof MePermissionDtoContextType[keyof typeof MePermissionDtoContextType];


export const MePermissionDtoContextType = {
  platform: 'platform',
  organization: 'organization',
} as const;

export interface MePermissionDto {
  key: string;
  name: string;
  module: string;
  contextType: MePermissionDtoContextType;
}

export interface AuthMeResponseDto {
  user: MeUserDto;
  organizations: MeOrganizationDto[];
  roles: MeRoleDto[];
  permissions: MePermissionDto[];
}

export interface AuthSessionResponseDto {
  accessToken: string;
  tokenType: string;
  me: AuthMeResponseDto;
}

export interface AuthRefreshResponseDto {
  accessToken: string;
  tokenType: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type healthGetHealthResponse200 = {
  data: HealthDto
  status: 200
}

export type healthGetHealthResponseSuccess = (healthGetHealthResponse200) & {
  headers: Headers;
};
;

export type healthGetHealthResponse = (healthGetHealthResponseSuccess)

export const getHealthGetHealthUrl = () => {




  return `/health`
}

export const healthGetHealth = async ( options?: RequestInit): Promise<healthGetHealthResponse> => {

  return customClient<healthGetHealthResponse>(getHealthGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthGetHealth>>> = ({ signal }) => healthGetHealth({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthGetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof healthGetHealth>>>
export type HealthGetHealthQueryError = unknown


export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Admin UI login — access token in body, refresh in HttpOnly cookie
 */
export type authAdminLoginResponse200 = {
  data: AuthLoginResponseDto
  status: 200
}

export type authAdminLoginResponse429 = {
  data: void
  status: 429
}

export type authAdminLoginResponseSuccess = (authAdminLoginResponse200) & {
  headers: Headers;
};
export type authAdminLoginResponseError = (authAdminLoginResponse429) & {
  headers: Headers;
};

export type authAdminLoginResponse = (authAdminLoginResponseSuccess | authAdminLoginResponseError)

export const getAuthAdminLoginUrl = () => {




  return `/api/auth/admin/login`
}

export const authAdminLogin = async (authLoginBodyDto: AuthLoginBodyDto, options?: RequestInit): Promise<authAdminLoginResponse> => {

  return customClient<authAdminLoginResponse>(getAuthAdminLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authLoginBodyDto,)
  }
);}




export const getAuthAdminLoginMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAdminLogin>>, TError,{data: AuthLoginBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authAdminLogin>>, TError,{data: AuthLoginBodyDto}, TContext> => {

const mutationKey = ['authAdminLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAdminLogin>>, {data: AuthLoginBodyDto}> = (props) => {
          const {data} = props ?? {};

          return  authAdminLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthAdminLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authAdminLogin>>>
    export type AuthAdminLoginMutationBody = AuthLoginBodyDto
    export type AuthAdminLoginMutationError = void

    /**
 * @summary Admin UI login — access token in body, refresh in HttpOnly cookie
 */
export const useAuthAdminLogin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAdminLogin>>, TError,{data: AuthLoginBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAdminLogin>>,
        TError,
        {data: AuthLoginBodyDto},
        TContext
      > => {
      return useMutation(getAuthAdminLoginMutationOptions(options), queryClient);
    }

/**
 * @summary Login — access token in body, refresh in HttpOnly cookie
 */
export type authLoginResponse200 = {
  data: AuthLoginResponseDto
  status: 200
}

export type authLoginResponse429 = {
  data: void
  status: 429
}

export type authLoginResponseSuccess = (authLoginResponse200) & {
  headers: Headers;
};
export type authLoginResponseError = (authLoginResponse429) & {
  headers: Headers;
};

export type authLoginResponse = (authLoginResponseSuccess | authLoginResponseError)

export const getAuthLoginUrl = () => {




  return `/api/auth/login`
}

export const authLogin = async (authLoginBodyDto: AuthLoginBodyDto, options?: RequestInit): Promise<authLoginResponse> => {

  return customClient<authLoginResponse>(getAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authLoginBodyDto,)
  }
);}




export const getAuthLoginMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyDto}, TContext> => {

const mutationKey = ['authLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogin>>, {data: AuthLoginBodyDto}> = (props) => {
          const {data} = props ?? {};

          return  authLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
    export type AuthLoginMutationBody = AuthLoginBodyDto
    export type AuthLoginMutationError = void

    /**
 * @summary Login — access token in body, refresh in HttpOnly cookie
 */
export const useAuthLogin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogin>>,
        TError,
        {data: AuthLoginBodyDto},
        TContext
      > => {
      return useMutation(getAuthLoginMutationOptions(options), queryClient);
    }

/**
 * @summary Create organization account — access token in body, refresh in HttpOnly cookie
 */
export type authSignupResponse201 = {
  data: AuthLoginResponseDto
  status: 201
}

export type authSignupResponse429 = {
  data: void
  status: 429
}

export type authSignupResponseSuccess = (authSignupResponse201) & {
  headers: Headers;
};
export type authSignupResponseError = (authSignupResponse429) & {
  headers: Headers;
};

export type authSignupResponse = (authSignupResponseSuccess | authSignupResponseError)

export const getAuthSignupUrl = () => {




  return `/api/auth/signup`
}

export const authSignup = async (authSignupBodyDto: AuthSignupBodyDto, options?: RequestInit): Promise<authSignupResponse> => {

  return customClient<authSignupResponse>(getAuthSignupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authSignupBodyDto,)
  }
);}




export const getAuthSignupMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authSignup>>, TError,{data: AuthSignupBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authSignup>>, TError,{data: AuthSignupBodyDto}, TContext> => {

const mutationKey = ['authSignup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authSignup>>, {data: AuthSignupBodyDto}> = (props) => {
          const {data} = props ?? {};

          return  authSignup(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthSignupMutationResult = NonNullable<Awaited<ReturnType<typeof authSignup>>>
    export type AuthSignupMutationBody = AuthSignupBodyDto
    export type AuthSignupMutationError = void

    /**
 * @summary Create organization account — access token in body, refresh in HttpOnly cookie
 */
export const useAuthSignup = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authSignup>>, TError,{data: AuthSignupBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authSignup>>,
        TError,
        {data: AuthSignupBodyDto},
        TContext
      > => {
      return useMutation(getAuthSignupMutationOptions(options), queryClient);
    }

/**
 * @summary Request password reset (organization app users only; same response whether email exists)
 */
export type authForgotPasswordResponse200 = {
  data: AuthMessageResponseDto
  status: 200
}

export type authForgotPasswordResponse429 = {
  data: void
  status: 429
}

export type authForgotPasswordResponseSuccess = (authForgotPasswordResponse200) & {
  headers: Headers;
};
export type authForgotPasswordResponseError = (authForgotPasswordResponse429) & {
  headers: Headers;
};

export type authForgotPasswordResponse = (authForgotPasswordResponseSuccess | authForgotPasswordResponseError)

export const getAuthForgotPasswordUrl = () => {




  return `/api/auth/forgot-password`
}

export const authForgotPassword = async (forgotPasswordBodyDto: ForgotPasswordBodyDto, options?: RequestInit): Promise<authForgotPasswordResponse> => {

  return customClient<authForgotPasswordResponse>(getAuthForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      forgotPasswordBodyDto,)
  }
);}




export const getAuthForgotPasswordMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authForgotPassword>>, TError,{data: ForgotPasswordBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authForgotPassword>>, TError,{data: ForgotPasswordBodyDto}, TContext> => {

const mutationKey = ['authForgotPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authForgotPassword>>, {data: ForgotPasswordBodyDto}> = (props) => {
          const {data} = props ?? {};

          return  authForgotPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authForgotPassword>>>
    export type AuthForgotPasswordMutationBody = ForgotPasswordBodyDto
    export type AuthForgotPasswordMutationError = void

    /**
 * @summary Request password reset (organization app users only; same response whether email exists)
 */
export const useAuthForgotPassword = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authForgotPassword>>, TError,{data: ForgotPasswordBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authForgotPassword>>,
        TError,
        {data: ForgotPasswordBodyDto},
        TContext
      > => {
      return useMutation(getAuthForgotPasswordMutationOptions(options), queryClient);
    }

/**
 * @summary Complete password reset with token from email link
 */
export type authResetPasswordResponse200 = {
  data: AuthMessageResponseDto
  status: 200
}

export type authResetPasswordResponse429 = {
  data: void
  status: 429
}

export type authResetPasswordResponseSuccess = (authResetPasswordResponse200) & {
  headers: Headers;
};
export type authResetPasswordResponseError = (authResetPasswordResponse429) & {
  headers: Headers;
};

export type authResetPasswordResponse = (authResetPasswordResponseSuccess | authResetPasswordResponseError)

export const getAuthResetPasswordUrl = () => {




  return `/api/auth/reset-password`
}

export const authResetPassword = async (resetPasswordBodyDto: ResetPasswordBodyDto, options?: RequestInit): Promise<authResetPasswordResponse> => {

  return customClient<authResetPasswordResponse>(getAuthResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordBodyDto,)
  }
);}




export const getAuthResetPasswordMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authResetPassword>>, TError,{data: ResetPasswordBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authResetPassword>>, TError,{data: ResetPasswordBodyDto}, TContext> => {

const mutationKey = ['authResetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authResetPassword>>, {data: ResetPasswordBodyDto}> = (props) => {
          const {data} = props ?? {};

          return  authResetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authResetPassword>>>
    export type AuthResetPasswordMutationBody = ResetPasswordBodyDto
    export type AuthResetPasswordMutationError = void

    /**
 * @summary Complete password reset with token from email link
 */
export const useAuthResetPassword = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authResetPassword>>, TError,{data: ResetPasswordBodyDto}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authResetPassword>>,
        TError,
        {data: ResetPasswordBodyDto},
        TContext
      > => {
      return useMutation(getAuthResetPasswordMutationOptions(options), queryClient);
    }

/**
 * @summary Admin UI bootstrap — issue access token and me from admin refresh cookie
 */
export type authAdminSessionResponse200 = {
  data: AuthSessionResponseDto
  status: 200
}

export type authAdminSessionResponseSuccess = (authAdminSessionResponse200) & {
  headers: Headers;
};
;

export type authAdminSessionResponse = (authAdminSessionResponseSuccess)

export const getAuthAdminSessionUrl = () => {




  return `/api/auth/admin/session`
}

export const authAdminSession = async ( options?: RequestInit): Promise<authAdminSessionResponse> => {

  return customClient<authAdminSessionResponse>(getAuthAdminSessionUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAuthAdminSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAdminSession>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authAdminSession>>, TError,void, TContext> => {

const mutationKey = ['authAdminSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAdminSession>>, void> = () => {


          return  authAdminSession(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthAdminSessionMutationResult = NonNullable<Awaited<ReturnType<typeof authAdminSession>>>

    export type AuthAdminSessionMutationError = unknown

    /**
 * @summary Admin UI bootstrap — issue access token and me from admin refresh cookie
 */
export const useAuthAdminSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAdminSession>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAdminSession>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthAdminSessionMutationOptions(options), queryClient);
    }

/**
 * @summary Admin UI — issue new access token using admin refresh cookie
 */
export type authAdminRefreshResponse200 = {
  data: AuthRefreshResponseDto
  status: 200
}

export type authAdminRefreshResponseSuccess = (authAdminRefreshResponse200) & {
  headers: Headers;
};
;

export type authAdminRefreshResponse = (authAdminRefreshResponseSuccess)

export const getAuthAdminRefreshUrl = () => {




  return `/api/auth/admin/refresh`
}

export const authAdminRefresh = async ( options?: RequestInit): Promise<authAdminRefreshResponse> => {

  return customClient<authAdminRefreshResponse>(getAuthAdminRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAuthAdminRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAdminRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authAdminRefresh>>, TError,void, TContext> => {

const mutationKey = ['authAdminRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAdminRefresh>>, void> = () => {


          return  authAdminRefresh(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthAdminRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authAdminRefresh>>>

    export type AuthAdminRefreshMutationError = unknown

    /**
 * @summary Admin UI — issue new access token using admin refresh cookie
 */
export const useAuthAdminRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAdminRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAdminRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthAdminRefreshMutationOptions(options), queryClient);
    }

/**
 * @summary Admin UI — revoke admin refresh session and clear cookie
 */
export type authAdminLogoutResponse204 = {
  data: void
  status: 204
}

export type authAdminLogoutResponseSuccess = (authAdminLogoutResponse204) & {
  headers: Headers;
};
;

export type authAdminLogoutResponse = (authAdminLogoutResponseSuccess)

export const getAuthAdminLogoutUrl = () => {




  return `/api/auth/admin/logout`
}

export const authAdminLogout = async ( options?: RequestInit): Promise<authAdminLogoutResponse> => {

  return customClient<authAdminLogoutResponse>(getAuthAdminLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAuthAdminLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAdminLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authAdminLogout>>, TError,void, TContext> => {

const mutationKey = ['authAdminLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAdminLogout>>, void> = () => {


          return  authAdminLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthAdminLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authAdminLogout>>>

    export type AuthAdminLogoutMutationError = unknown

    /**
 * @summary Admin UI — revoke admin refresh session and clear cookie
 */
export const useAuthAdminLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAdminLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAdminLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthAdminLogoutMutationOptions(options), queryClient);
    }

/**
 * @summary Issue access token and me using refresh cookie
 */
export type authSessionResponse200 = {
  data: AuthSessionResponseDto
  status: 200
}

export type authSessionResponseSuccess = (authSessionResponse200) & {
  headers: Headers;
};
;

export type authSessionResponse = (authSessionResponseSuccess)

export const getAuthSessionUrl = () => {




  return `/api/auth/session`
}

export const authSession = async ( options?: RequestInit): Promise<authSessionResponse> => {

  return customClient<authSessionResponse>(getAuthSessionUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAuthSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authSession>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authSession>>, TError,void, TContext> => {

const mutationKey = ['authSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authSession>>, void> = () => {


          return  authSession(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthSessionMutationResult = NonNullable<Awaited<ReturnType<typeof authSession>>>

    export type AuthSessionMutationError = unknown

    /**
 * @summary Issue access token and me using refresh cookie
 */
export const useAuthSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authSession>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authSession>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthSessionMutationOptions(options), queryClient);
    }

/**
 * @summary Issue new access token using refresh cookie
 */
export type authRefreshResponse200 = {
  data: AuthRefreshResponseDto
  status: 200
}

export type authRefreshResponseSuccess = (authRefreshResponse200) & {
  headers: Headers;
};
;

export type authRefreshResponse = (authRefreshResponseSuccess)

export const getAuthRefreshUrl = () => {




  return `/api/auth/refresh`
}

export const authRefresh = async ( options?: RequestInit): Promise<authRefreshResponse> => {

  return customClient<authRefreshResponse>(getAuthRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAuthRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authRefresh>>, TError,void, TContext> => {

const mutationKey = ['authRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRefresh>>, void> = () => {


          return  authRefresh(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authRefresh>>>

    export type AuthRefreshMutationError = unknown

    /**
 * @summary Issue new access token using refresh cookie
 */
export const useAuthRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthRefreshMutationOptions(options), queryClient);
    }

/**
 * @summary Revoke refresh session and clear cookie
 */
export type authLogoutResponse204 = {
  data: void
  status: 204
}

export type authLogoutResponseSuccess = (authLogoutResponse204) & {
  headers: Headers;
};
;

export type authLogoutResponse = (authLogoutResponseSuccess)

export const getAuthLogoutUrl = () => {




  return `/api/auth/logout`
}

export const authLogout = async ( options?: RequestInit): Promise<authLogoutResponse> => {

  return customClient<authLogoutResponse>(getAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAuthLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext> => {

const mutationKey = ['authLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {


          return  authLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>

    export type AuthLogoutMutationError = unknown

    /**
 * @summary Revoke refresh session and clear cookie
 */
export const useAuthLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthLogoutMutationOptions(options), queryClient);
    }

/**
 * @summary Current user, orgs, roles, permissions
 */
export type authMeResponse200 = {
  data: AuthMeResponseDto
  status: 200
}

export type authMeResponseSuccess = (authMeResponse200) & {
  headers: Headers;
};
;

export type authMeResponse = (authMeResponseSuccess)

export const getAuthMeUrl = () => {




  return `/api/auth/me`
}

export const authMe = async ( options?: RequestInit): Promise<authMeResponse> => {

  return customClient<authMeResponse>(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAuthMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const getAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMe>>> = ({ signal }) => authMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>
export type AuthMeQueryError = unknown


export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Current user, orgs, roles, permissions
 */

export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
