/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Starter API
 * Backend API for the starter template
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customClient } from './api-client';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type healthGetHealthResponse200 = {
  data: unknown;
  status: 200;
};

export type healthGetHealthResponseSuccess = healthGetHealthResponse200 & {
  headers: Headers;
};
export type healthGetHealthResponse = healthGetHealthResponseSuccess;

export const getHealthGetHealthUrl = () => {
  return `/health`;
};

export const healthGetHealth = async (options?: RequestInit): Promise<healthGetHealthResponse> => {
  return customClient<healthGetHealthResponse>(getHealthGetHealthUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getHealthGetHealthQueryKey = () => {
  return [`/health`] as const;
};

export const getHealthGetHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthGetHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthGetHealth>>> = ({ signal }) =>
    healthGetHealth({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthGetHealth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthGetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof healthGetHealth>>>;
export type HealthGetHealthQueryError = unknown;

export function useHealthGetHealth<
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHealthGetHealth<
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHealthGetHealth<
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useHealthGetHealth<
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>;
    request?: SecondParameter<typeof customClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthGetHealthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
